### ISSUE TITLE
Screen deletion

### ISSUE THREAD

**Issue by gigili** [negue/meme-box#68] opened 2020-08-15 16:26 UTC
After deleting the only screen that was added this showed up:
![meme-box-delete-screen](https://user-images.githubusercontent.com/2153382/90316749-a0558f80-df24-11ea-83c9-ef3057ec9225.png)

After refreshing the page I was able to add/delete new screens. And the error didn't show up again.  

After deleting a screen (the only screen that exists) and than adding a new one it imports all the media from the media page.

It might be annoying having to go and unselect a lot of media if you have a large library. And don't want them all on the same screen.

**Comment by negue** [comment] 2020-08-15 16:35
Couldn't reproduce this issue yet :/

> It might be annoying having to go and unselect a lot of media if you have a large library. And don't want them all on the same screen.

This was exactly added to have atleast one screen with screens you have ... maybe @whitep4nth3r has an idea for that.

**Comment by gigili** [comment] 2020-11-16 22:31
Should we close this one as it seems to be one off kind of an error that can't be reproduced ?

**Comment by negue** [comment] 2020-11-17 23:51
Yeah we can close it, these issue is probably already fixed since then.

**Closed by negue** 2020-11-17 23:51 UTC
